name: build
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: "! ( contains(github.event.head_commit.message, 'maven-release-plugin') || contains(github.event.head_commit.message, 'skip ci') )"
    #container: maven:3-adoptopenjdk-15
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4

    - name: Setup java
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: '11'
        overwrite-settings: false

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.1
      with:
        maven-version: 3.8.1

    - name: Run build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ECR_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_ACCESS_KEY_SECRET }}
        AWS_DEFAULT_REGION: eu-north-1
      run: |
        mvn clean deploy -Ddocker.registry=931692337119.dkr.ecr.eu-north-1.amazonaws.com
