name: build
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: "! ( contains(github.event.head_commit.message, 'maven-release-plugin') || contains(github.event.head_commit.message, 'skip ci') )"
    #container: maven:3-adoptopenjdk-15
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4

    - uses: brpaz/hadolint-action@v1.1.0

    - name: Setup java
      uses: actions/setup-java@v2.2.0
      with:
        distribution: temurin
        java-version: 11
        overwrite-settings: false

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.1
      with:
        maven-version: 3.8.1

    - name: Login to QUAY
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Run build
      run: |
        mvn clean deploy -Ddocker.registry=quay.io
